export const BGM = {
    home:         '/music/HomeBackTrack.mp3',
    feed:         '/music/FeedBackTrack.mp3',
    chat:         '/music/ChatBackTrack.mp3',
    admin:        '/music/AdminBackTrack.mp3',
    community:    '/music/CommunitySong4.mp3',
    friends:      '/music/FriendsPage.mp3',
    communities:  '/music/CommunitySong4.mp3',
    profile_own:  '/music/Profile1.mp3',
    profile_other:'/music/Profile2.mp3',
};

export const SFX = {
    click1:            '/music/Click1.mp3',
    click2:            '/music/Click2.mp3',
    back:              '/music/Back.mp3',
    bubbleExpand:      '/music/BubbleExpand.mp3',
    bubbleExpand2:     '/music/BubbleExpand2.mp3',
    bubbleExpand3:     '/music/BubbleExpand3.mp3',
    passMouseOnBubble: '/music/PassMouseOnBubble.mp3',
    feedBox:           '/music/FeedBox.mp3',
    join:              '/music/Join.mp3',
    send:              '/music/Send.mp3',
    off:               '/music/off.mp3',
    persons:           '/music/Persons.mp3',
    persons2:          '/music/Persons2.mp3',
    persons3:          '/music/Persons3.mp3',
    leave:             '/music/Leave.mp3',
    notification:      '/music/Notification.mp3',
    openGlobal:        '/music/OpenGlobal.mp3',
    closeGlobal:       '/music/CloseGlobal.mp3',
    enterCommunity1:   '/music/EnterCommunity1.mp3',
    enterCommunity2:   '/music/EnterCommunity2.mp3',
    enterCommunity3:   '/music/EnterCommunity3.mp3',
    buttonAdmin:       '/music/ButtonAdmin.mp3',
    buttonAdmin2:      '/music/ButtonAdmin2.mp3',
    buttonAdmin3:      '/music/ButtonAdmin3.mp3',
    pageChange:        '/music/PageChange.mp3',
    created:           '/music/Created.mp3',
};
